# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#080e15"

# Main text color
theme[main_fg]="#d0cbb2"

# Title color for boxes
theme[title]="#dcd8c5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9ba4bb"

# Background color of selected item in processes box
theme[selected_bg]="#21262c"

# Foreground color of selected item in processes box
theme[selected_fg]="#9ba4bb"

# Color of inactive/disabled text
theme[inactive_fg]="#63676c"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d7d3be"

# Background color of the percentage meters
theme[meter_bg]="#21262c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d7d3be"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#9ba4bb"
theme[mem_box]="#967150"
theme[net_box]="#8c7666"
theme[proc_box]="#7d819c"

# Box divider line and small boxes line color
theme[div_line]="#63676c"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#967150"
theme[temp_mid]="#9a927a"
theme[temp_end]="#8c7666"

# CPU graph colors (Cyan -> Accent)
theme[cpu_start]="#83a2a3"
theme[cpu_mid]="#83a2a3"
theme[cpu_end]="#9ba4bb"

# Mem/Disk free meter (Accent -> Light)
theme[free_start]="#9ba4bb"
theme[free_mid]="#c0c9e7"
theme[free_end]="#d0cbb2"

# Mem/Disk cached meter (Cyan -> Accent)
theme[cached_start]="#83a2a3"
theme[cached_mid]="#9ba4bb"
theme[cached_end]="#c0c9e7"

# Mem/Disk available meter (Red -> Orange)
theme[available_start]="#8c7666"
theme[available_mid]="#b39a85"
theme[available_end]="#b39a85"

# Mem/Disk used meter (Green -> Cyan)
theme[used_start]="#967150"
theme[used_mid]="#83a2a3"
theme[used_end]="#a5c9ca"

# Download graph colors (Red -> Orange)
theme[download_start]="#8c7666"
theme[download_mid]="#b39a85"
theme[download_end]="#b39a85"

# Upload graph colors (Green -> Cyan)
theme[upload_start]="#967150"
theme[upload_mid]="#83a2a3"
theme[upload_end]="#a5c9ca"

# Process box color gradient for threads, mem and cpu usage (Cyan -> Accent)
theme[process_start]="#83a2a3"
theme[process_mid]="#9ba4bb"
theme[process_end]="#c0c9e7"
