window-decoration = none

# Font
font-family = "FiraCode Nerd Font"
font-size = 9
font-style = Bold
font-style-bold = ExtraBold
font-style-italic = Italic
font-feature = +liga, +dlig, +calt

# Looks
theme = Catppuccin Mocha
background-opacity = 1
background-blur = true

# Window
window-padding-x = 16
window-padding-y = 16
confirm-close-surface=false
resize-overlay = never

# Cursor stlying
cursor-style = "bar"
cursor-style-blink = false
shell-integration-features = no-cursor

palette = 0=#080e15
palette = 1=#8c7666
palette = 2=#967150
palette = 3=#9a927a
palette = 4=#9ba4bb
palette = 5=#7d819c
palette = 6=#83a2a3
palette = 7=#d0cbb2
palette = 8=#21262c
palette = 9=#b39a85
palette = 10=#74543A
palette = 11=#c0b898
palette = 12=#c0c9e7
palette = 13=#a1a4c7
palette = 14=#a5c9ca
palette = 15=#dcd8c5
background = 080e15
foreground = d0cbb2
cursor-color = 9ba4bb
cursor-text = 080e15
selection-background = 9ba4bb
selection-foreground = 080e15
split-divider-color = 21262c
